"""ایموجی‌های مرکزی"""
E = {
    "bolt":     "⚡",
    "fire":     "🔥",
    "star":     "⭐",
    "check":    "✅",
    "cross":    "❌",
    "warn":     "⚠️",
    "info":     "ℹ️",
    "gear":     "⚙️",
    "rocket":   "🚀",
    "download": "📥",
    "upload":   "📤",
    "folder":   "📁",
    "file":     "📄",
    "clock":    "⏱",
    "hourglass":"⏳",
    "chart":    "📊",
    "crown":    "👑",
    "shield":   "🛡️",
    "video":    "🎬",
    "image":    "🖼️",
    "audio":    "🎵",
    "pdf":      "📕",
    "archive":  "📦",
    "gif":      "🎞️",
    "back":     "◀",
    "next":     "▶",
    "home":     "🏠",
    "trash":    "🗑️",
    "sparkle":  "✨",
    "trophy":   "🏆",
    "medal1":   "🥇",
    "medal2":   "🥈",
    "medal3":   "🥉",
}
